#!/usr/bin/env python3
"""Generate LaTeX Tables 2 & 3 from data/vulnerabilities.yaml.
Uses only Python stdlib — no PyYAML required.
"""
import re
import os

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(SCRIPT_DIR, "..", "data", "vulnerabilities.yaml")
OUT  = os.path.join(SCRIPT_DIR, "..", "tables")

os.makedirs(OUT, exist_ok=True)


def parse_scanners(s):
    """Parse { kics: "...", trivy: KSV012, ... } into a dict."""
    result = {}
    s = s.strip().lstrip("{").rstrip("}")
    for m in re.finditer(r'(\w+):\s*(?:"([^"]*?)"|([^,}]+?))\s*(?:,|$)', s):
        key = m.group(1)
        val = (m.group(2) if m.group(2) is not None else m.group(3)).strip()
        result[key] = val
    return result


def parse_vulns(path):
    entries = []
    cur = {}
    with open(path, encoding="utf-8") as f:
        for raw in f:
            line = raw.rstrip()
            if line.startswith("- id:"):
                if cur:
                    entries.append(cur)
                cur = {"id": line.split(":", 1)[1].strip()}
            elif line.startswith("  ") and ":" in line and not line.strip().startswith("#"):
                key, _, val = line.strip().partition(":")
                val = val.strip().strip('"')
                if key == "scanners":
                    cur["scanners"] = parse_scanners(val)
                elif key == "cwe":
                    cur["cwe"] = val  # keep as string
                else:
                    cur[key] = val
    if cur:
        entries.append(cur)
    return entries


def escape_id(s):
    return s.replace("-", "\\-")


def truncate_kics(s):
    if len(s) > 8 and s != "---":
        return s[:8] + r"\ldots"
    return s


LONGTABLE_HEADER_INVENTORY = r"""% Generated by scripts/gen-tables.py — do not edit manually
\begin{longtable}{@{}lp{5cm}cclll@{}}
\caption{MAD Goat Kubernetes Vulnerability Inventory}\label{tab:vuln-inventory}\\
\toprule
\textbf{ID} & \textbf{Title} & \textbf{2025} & \textbf{2022} & \textbf{CWE} & \textbf{CIS} & \textbf{Scope} \\
\midrule
\endfirsthead
\multicolumn{7}{c}{\tablename\ \thetable{} (continued)}\\
\toprule
\textbf{ID} & \textbf{Title} & \textbf{2025} & \textbf{2022} & \textbf{CWE} & \textbf{CIS} & \textbf{Scope} \\
\midrule
\endhead
\midrule
\multicolumn{7}{r}{\textit{Continued on next page}}\\
\endfoot
\bottomrule
\endlastfoot
"""

LONGTABLE_HEADER_SCANNERS = r"""% Generated by scripts/gen-tables.py — do not edit manually
\begin{longtable}{@{}lp{3.2cm}p{2cm}p{2.4cm}p{2cm}@{}}
\caption{Static Analysis Scanner Coverage per Vulnerability}\label{tab:scanner-coverage}\\
\toprule
\textbf{ID} & \textbf{KICS} & \textbf{Trivy} & \textbf{KubeLinter} & \textbf{Kubescape} \\
\midrule
\endfirsthead
\multicolumn{5}{c}{\tablename\ \thetable{} (continued)}\\
\toprule
\textbf{ID} & \textbf{KICS} & \textbf{Trivy} & \textbf{KubeLinter} & \textbf{Kubescape} \\
\midrule
\endhead
\midrule
\multicolumn{5}{r}{\textit{Continued on next page}}\\
\endfoot
\bottomrule
\endlastfoot
"""


def write_inventory(entries, path):
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(LONGTABLE_HEADER_INVENTORY)
        for e in entries:
            eid    = escape_id(e.get("id", ""))
            title  = e.get("title", "")
            y2025  = e.get("owasp2025", "")
            y2022  = e.get("owasp2022", "") or "---"
            cwe    = "CWE-" + e.get("cwe", "")
            cis    = e.get("cis", "") or "---"
            scope  = e.get("scope", "")
            f.write(f"\\texttt{{{eid}}} & {title} & {y2025} & {y2022} & {cwe} & {cis} & {scope} \\\\\n")
        f.write(r"\end{longtable}" + "\n")


def write_scanners(entries, path):
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(LONGTABLE_HEADER_SCANNERS)
        for e in entries:
            eid  = escape_id(e.get("id", ""))
            sc   = e.get("scanners", {})
            kics = truncate_kics(sc.get("kics", "") or "---")
            trivy = sc.get("trivy", "") or "---"
            kl   = sc.get("kubelinter", "") or "---"
            ks   = sc.get("kubescape", "") or "---"
            f.write(
                f"\\texttt{{{eid}}} & \\texttt{{\\scriptsize {kics}}} & "
                f"\\texttt{{{trivy}}} & \\texttt{{\\scriptsize {kl}}} & \\texttt{{{ks}}} \\\\\n"
            )
        f.write(r"\end{longtable}" + "\n")


if __name__ == "__main__":
    entries = parse_vulns(DATA)
    inv_path = os.path.join(OUT, "vuln-inventory.tex")
    sc_path  = os.path.join(OUT, "scanner-coverage.tex")
    write_inventory(entries, inv_path)
    write_scanners(entries, sc_path)
    print(f"Generated: {inv_path}")
    print(f"Generated: {sc_path}")