apiVersion: v1
kind: Service
metadata:
  labels:
    io.mad.service: docs
  name: docs
spec:
  ports:
    - name: "4000"
      port: 4000
      targetPort: 80
  selector:
    io.mad.service: docs
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-prefix-docs
spec:
  stripPrefixRegex:
    regex:
      - "/api/docs"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: docs
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`madgoat.tech`) && PathPrefix(`/api/docs`)
      middlewares:
          - name: strip-prefix-docs
      services:
        - kind: Service
          name: docs
          namespace: default
          port: 80