apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.mad.service: docs
  name: docs
spec:
  replicas: 1
  selector:
    matchLabels:
      io.mad.service: docs
  template:
    metadata:
      labels:

        io.mad.service: docs
    spec:
      containers:
        - image: ghcr.io/mad-goat-project/mad-goat-docs:main
          name: docs
          ports:
            - containerPort: 4000
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: "500Mi"
            requests:
              cpu: 250m
              memory: "250Mi"
      restartPolicy: Always
