apiVersion: v1
kind: Pod
metadata:
  name: file-copy-pod
  labels:
    name: file-copy-pod
spec:
  containers:
    - name: file-copy-container
      image: busybox
      command:
        - "sh"
        - "-c"
        - "chmod -R 777 /keycloak /lesson && sleep 3000" # Keep pod running until file operation completes
      volumeMounts:
        - mountPath: /keycloak
          name: db-keycloak-claim0
        - mountPath: /lesson
          name: db-lesson-claim0
      securityContext:
        runAsUser: 0 # Run as root user
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
  volumes:
    - name: db-lesson-claim0
      persistentVolumeClaim:
        claimName: db-lesson-claim0
    - name: db-keycloak-claim0
      persistentVolumeClaim:
        claimName: db-keycloak-claim0
  restartPolicy: Never