apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.mad.service: db-lesson
  name: db-lesson
spec:
  replicas: 1
  selector:
    matchLabels:
      io.mad.service: db-lesson
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.mad.network/mad-network: "true"
        io.mad.service: db-lesson
    spec:
      initContainers:
        - name: default-database-loader
          image: ghcr.io/mad-goat-project/db-lesson:data
          env:
            - name: TARGET_PATH
              value: "/var/lib/postgresql/data"  # Destination path inside the pod
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db-lesson-claim0
      containers:
        - envFrom:
            - configMapRef:
                name: env-lesson
          image: postgres:14.1-alpine
          name: db-lesson
          ports:
            - containerPort: 5432
          resources:
            limits:
              cpu: 500m
              memory: "500Mi"
            requests:
              cpu: 250m
              memory: "250Mi"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db-lesson-claim0
      restartPolicy: Always
      volumes:
        - name: db-lesson-claim0
          persistentVolumeClaim:
            claimName: db-lesson-claim0
