apiVersion: v1
kind: Service
metadata:
  labels:
    io.mad.service: db-lesson
  name: db-lesson
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    io.mad.service: db-lesson
