apiVersion: v1
kind: Service
metadata:
  labels:
    io.mad.service: db-scoreboard
  name: db-scoreboard
spec:
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
  selector:
    io.mad.service: db-scoreboard
