apiVersion: v1
kind: Service
metadata:
  labels:
    io.mad.service: mad-lesson-service
  name: mad-lesson-service
spec:
  ports:
    - name: "3001"
      port: 3001
      targetPort: 3000
  selector:
    io.mad.service: mad-lesson-service
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-prefix-lessons
spec:
  stripPrefixRegex:
    regex:
      - "/lessons"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: mad-lesson-service
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`api.mad.localhost`) && PathPrefix(`/lessons`)
      middlewares:
        - name: strip-prefix-lessons
      services:
        - kind: Service
          name: mad-lesson-service
          namespace: default
          port: 3000
