apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.mad.service: db-keycloak-service
  name: db-keycloak-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.mad.service: db-keycloak-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.mad.network/mad-network: "true"
        io.mad.service: db-keycloak-service
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: env-keycloak
          image: postgres:15.3-alpine
          name: db-keycloak-service
          ports:
            - containerPort: 5432
          resources:
            limits:
              cpu: 500m
              memory: "500Mi"
            requests:
              cpu: 250m
              memory: "250Mi"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db-keycloak-service-claim
      restartPolicy: Always
      volumes:
        - name: db-keycloak-service-claim
          hostPath:
            path: /host/compose/data/db-keycloak-service
            type: DirectoryOrCreate