apiVersion: v1
kind: Service
metadata:
  labels:
    io.mad.service: mad-keycloak-service
  name: mad-keycloak-service
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.mad.service: mad-keycloak-service
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: mad-keycloak-service
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`keycloak.mad.localhost`) && PathPrefix(`/`) && (Method(`GET`) || Method(`POST`))
      services:
        - kind: Service
          name: mad-keycloak-service
          namespace: default
          port: 8080