apiVersion: v1
kind: Service
metadata:
  labels:
    io.mad.service: mad-keycloak
  name: mad-keycloak
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.mad.service: mad-keycloak
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-prefix-keycloak
spec:
  stripPrefixRegex:
    regex:
      - "/keycloak"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: mad-keycloak
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: PathPrefix(`/keycloak`) && (Method(`GET`) || Method(`POST`))
      middlewares:
        - name: strip-prefix-keycloak
      services:
        - kind: Service
          name: mad-keycloak
          namespace: default
          port: 8080