apiVersion: v1
kind: Service
metadata:
  labels:
    io.mad.service: mad-profile
  name: mad-profile
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    io.mad.service: mad-profile
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-prefix-profile
spec:
  stripPrefixRegex:
    regex:
      - "/api/profile"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: mad-profile
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`madgoat.tech`) && PathPrefix(`/api/profile`)
      middlewares:
        - name: strip-prefix-profile
      services:
        - kind: Service
          name: mad-profile
          namespace: default
          port: 3000
