apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.mad.service: profile
  name: profile
spec:
  replicas: 1
  selector:
    matchLabels:
      io.mad.service: profile
  template:
    metadata:
      labels:
        io.mad.service: profile
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: env-profile
            - configMapRef:
                name: env-keycloak-secrets
          image: ghcr.io/mad-goat-project/mad-profile-service:main
          name: mad-profile
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: "500Mi"
            requests:
              cpu: 250m
              memory: "250Mi"
      restartPolicy: Always
