apiVersion: v1
kind: Service
metadata:
  labels:
    io.mad.service: webapp
  name: webapp
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 80
  selector:
    io.mad.service: webapp
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: webapp
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`madgoat.tech`) && PathPrefix(`/`)
      services:
        - kind: Service
          name: webapp
          namespace: default
          port: 3000
