apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.mad.service: webapp
  name: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      io.mad.service: webapp
  strategy: {}
  template:
    metadata:
      labels:
        io.mad.service: webapp
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: env-webapp
          image: ghcr.io/mad-goat-project/mad-web-app:madgoat-tech
          name: mad-web-app
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 500m
              memory: "500Mi"
            requests:
              cpu: 250m
              memory: "250Mi"
      restartPolicy: Always
