apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.mad.service: db-keycloak-claim0
  name: db-keycloak-claim0
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi