apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.mad.service: mad-keycloak
  name: mad-keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      io.mad.service: mad-keycloak
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.mad.service: mad-keycloak
    spec:
      initContainers:
        - name: initialize-realm
          envFrom:
            - configMapRef:
                name: env-keycloak
          image: ghcr.io/mad-goat-project/keycloak:main
          args:
            - "import"
            - "--file"
            - "/cfg-mount/MADGoat-config.json"
          volumeMounts:
            - mountPath: /cfg-mount
              name: keycloak-init-mount
      containers:
        - envFrom:
            - configMapRef:
                name: env-keycloak
          image: ghcr.io/mad-goat-project/keycloak:main
          args:
            - "start-dev"
          name: mad-keycloak
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
              memory: "500Mi"
            requests:
              cpu: 250m
              memory: "250Mi"
      restartPolicy: Always
      volumes:
      - name: keycloak-init-mount
        configMap:
          name: realm-config
          items:
            - key: "realm-config.json"
              path: "MADGoat-config.json"