apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      io.mad.service: minio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.mad.service: minio
    spec:
      initContainers:
        - name: default-minio-loader
          image: ghcr.io/mad-goat-project/minio:data
          env:
            - name: TARGET_PATH
              value: "/minio-data"  # Destination path inside the pod
          volumeMounts:
            - mountPath: /minio-data
              name: minio-claim0
      containers:
        - args:
            - server
            - /data
            - --console-address
            - :9001
          envFrom:
            - configMapRef:
                name: env-minio
          image: ghcr.io/mad-goat-project/mc-minio:mc-minio
          name: minio
          ports:
            - containerPort: 9000
              protocol: TCP
            - containerPort: 9001
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: minio-claim0
          resources:
            limits:
              cpu: 500m
              memory: "500Mi"
            requests:
              cpu: 250m
              memory: "256Mi"
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - |
                    sleep 5  # Give MinIO time to initialize
                    mc alias set local http://localhost:9000 minio minio123
                    mc admin info local
                    mc mb local/mad-images
                    mc anonymous set public local/mad-images
      restartPolicy: Always
      volumes:
        - name: minio-claim0
          persistentVolumeClaim:
            claimName: minio-claim0