madServices:
  - deployment:
      image: ghcr.io/mad-goat-project/mad-lessons-service:main
      resources:
        limits:
          memory: "512Mi"
          cpu: "500m"
        requests:
          memory: "256Mi"
          cpu: "250m"
      ports:
        - containerPort: 3000
          protocol: TCP
      envFromConfigMaps:
        - env-lesson
        - env-keycloak-secrets
    service:
      ports:
        - name: "3000"
          port: 3000
          targetPort: 3000
      traefik:
        routes:
          - name: lesson
            service:
              name: lesson
              port: 3000
            middleware:
              name: strip-prefix-lessons
              stripPrefix: "/api/lessons"

  - name: docs
    deployment:
      image: ghcr.io/mad-goat-project/mad-goat-docs:main
      resources:
        limits:
          memory: "512Mi"
          cpu: "500m"
        requests:
          memory: "256Mi"
          cpu: "250m"
      ports:
        - containerPort: 4000
          protocol: TCP
    service:
      ports:
        - name: "4000"
          port: 4000
          targetPort: 80
      traefik:
        routes:
          - name: docs
            service:
              name: docs
              port: 80
            middleware:
              name: strip-prefix-docs
              stripPrefix: "/api/docs"

  - name: profile
    deployment:
      image: ghcr.io/mad-goat-project/mad-profile-service:main
      resources:
        limits:
          memory: "512Mi"
          cpu: "500m"
        requests:
          memory: "256Mi"
          cpu: "250m"
      ports:
        - containerPort: 3000
          protocol: TCP
      envFromConfigMaps:
        - env-profile
        - env-keycloak-secrets
    service:
      ports:
        - name: "3000"
          port: 3000
          targetPort: 3000
      traefik:
        routes:
          - name: profile
            service:
              name: profile
              port: 3000
            middleware:
              name: strip-prefix-profile
              stripPrefix: "/api/profile"

  - name: scoreboard
    deployment:
      image: ghcr.io/mad-goat-project/mad-scoreboard-service:main
      resources:
        limits:
          memory: "512Mi"
          cpu: "500m"
        requests:
          memory: "256Mi"
          cpu: "250m"
      ports:
        - containerPort: 3000
          protocol: TCP
      envFromConfigMaps:
        - env-scoreboard
        - env-keycloak-secrets
    service:
      ports:
        - name: "3004"
          port: 3004
          targetPort: 3000
      traefik:
        routes:
          - name: scoreboard
            service:
              name: scoreboard
              port: 3004
            middleware:
              name: strip-prefix-scoreboard
              stripPrefix: "/api/scoreboard"

  - name: webapp
    deployment:
      image: ghcr.io/mad-goat-project/mad-web-app:madgoat-tech
      resources:
        limits:
          memory: "512Mi"
          cpu: "500m"
        requests:
          memory: "256Mi"
          cpu: "250m"
      ports:
        - containerPort: 80
          protocol: TCP
      envFromConfigMaps:
        - env-webapp
    service:
      ports:
        - name: "3000"
          port: 3000
          targetPort: 80
      traefik:
        routes:
          - name: webapp
            service:
              name: webapp
              port: 3000
      middleware:

  - name: mad4shell-safe
    deployment:
      image: ghcr.io/mad-goat-project/mad-goat4shell-service:safe
      resources:
        limits:
          memory: "512Mi"
          cpu: "500m"
        requests:
          memory: "256Mi"
          cpu: "250m"
      ports:
        - containerPort: 8080
          protocol: TCP
    service:
      ports:
        - name: "3002"
          port: 3002
          targetPort: 8080
      traefik:
        routes:
          - name: mad4shell-safe
            service:
              name: mad4shell-safe
              port: 3002
            middleware:
              name: strip-prefix-safe
              stripPrefix: "/api/goat4shell-safe"

  - name: mad4shell-unsafe
    deployment:
      image: ghcr.io/mad-goat-project/mad-goat4shell-service:unsafe
      resources:
        limits:
          memory: "512Mi"
          cpu: "500m"
        requests:
          memory: "256Mi"
          cpu: "250m"
      ports:
        - containerPort: 8080
          protocol: TCP
    service:
      ports:
        - name: "3003"
          port: 3003
          targetPort: 8080
      traefik:
        routes:
          - name: mad4shell-unsafe
            service:
              name: mad4shell-unsafe
              port: 3003
            middleware:
              name: strip-prefix-unsafe
              stripPrefix: "/api/goat4shell-unsafe"
