configMaps:
  - name: env-lesson
    data:
      DB_HOST: "db-lesson"
      DB_PORT: "5432"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "postgres"
      DB_NAME: "lessons"

      # Lesson Database"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "lessons"

      # RabbitMQ"
      RMQ_PRODUCER_QUEUE: "lesson_completed_queue"
      RMQ_PRODUCER_URL: "amqp://guest:guest@rabbitmq:5672"
      RMQ_PRODUCER_QUEUE_DURABLE: "true"

      NODE_ENV: "development"
  - name: env-profile
    data:
      GO_ENV: "production"
      GO_PORT: "3000"
      JWT_SECRET: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvGJSXMLY2fKdoN/D0oTYekvandITVIUAnIn719MQ5fQFg3TuEU5F9YU5l+VCkp4c4isW4ozpiQiJdFp8xnQfIiizO8LohNJbajzxkwvhqNsy9HqR1/iDD5zoroksvsCS7TPmM9J5bkgqhNGdK1hHJX91De3RLQfcQY9ZDYE6+NX3fAzuK9jx5TJc9k2KRJofniv/1RMaOaUhleP1ljdxI1ttyvU6FZCMCJoNAFVIXaPtA3/1jSJCE37XWORoWPG6Ri2d5rDwioJxc5rllTM/Av07qdXZVt446YFjwUoT113IbxAzX6fY2Mh48doKertXlkPcVcmrcOoivoxRp4KzQwIDAQAB"
  - name: env-webapp
    data:
      # Web Application
      VITE_KEYCLOAK_URL: "keycloak.madgoat.tech"
      VITE_KEYCLOAK_REALM: "MADGoat"
      VITE_KEYCLOAK_CLIENT_ID: "mad-goat-web-app"

      VITE_LESSON_BASE_URL: "http://madgoat.tech/api/lessons"
      VITE_GOAT4SHELL_BASE_URL: "http://madgoat.tech/api/goat4shell-unsafe"
      VITE_SCOREBOARD_BASE_URL: "http://madgoat.tech/api/scoreboard"
      VITE_DOCS_BASE_URL: "http://madgoat.tech/api/docs"
      VITE_PROFILE_BASE_URL: "http://madgoat.tech/profile/api/v1"
      VITE_OBJECT_STORAGE_BASE_URL: "http://madgoat.tech/s3/mad-images"
  - name: env-keycloak-secrets
    data:
      KC_CLIENT_ID: "mad-goat-services"
      KC_REALM: "MADGoat"
      KC_SECRET: "RvWEVib2wgZRr7DnOIQzW1JISiNWSHhz"
      KC_SERVER_URL: "http://keycloak.madgoat.tech"
  - name: env-scoreboard
    data:
      MONGO_CONNECTION_STRING: "mongodb://root:root@db-scoreboard:27017/?retryWrites=false&serverSelectionTimeoutMS=5000&connectTimeoutMS=10000&authSource=admin&authMechanism=SCRAM-SHA-256"
      MONGO_DATABASE_NAME: "scoreboard"
      MONGO_INITDB_ROOT_PASSWORD: "root"
      MONGO_INITDB_ROOT_USERNAME: "root"
      PORT: "3000"
      RMQ_PRODUCER_QUEUE: "lesson_completed_queue"
      RMQ_PRODUCER_QUEUE_DURABLE: "true"
      RMQ_PRODUCER_URL: "amqp://guest:guest@mad-rabbitmq:5672"