madServices:

  - name: lesson
    deployment:
      image: ghcr.io/mad-goat-project/mad-lessons-service:main
      ports:
        - containerPort: 3000
          protocol: TCP
      envFromConfigMaps:
        - env-lesson
        - env-keycloak-secrets
    service:
      type: ClusterIP
      ports:
        - name: "3000"
          port: 3000
          targetPort: 3000

  - name: docs
    deployment:
      image: ghcr.io/mad-goat-project/mad-goat-docs:main
      ports:
        - containerPort: 4000
          protocol: TCP

  - name: profile
    deployment:
      image: ghcr.io/mad-goat-project/mad-profile-service:main
      ports:
        - containerPort: 3000
          protocol: TCP
      envFromConfigMaps:
        - env-profile
        - env-keycloak-secrets

  - name: scoreboard
    deployment:
      image: ghcr.io/mad-goat-project/mad-scoreboard-service:main
      ports:
        - containerPort: 3000
          protocol: TCP
      envFromConfigMaps:
        - env-scoreboard
        - env-keycloak-secrets

  - name: webapp
    deployment:
      image: ghcr.io/mad-goat-project/mad-web-app:madgoat-tech
      ports:
        - containerPort: 80
          protocol: TCP

configMaps: