apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.mad.service: mad-lesson
  name: mad-lesson
spec:
  replicas: 1
  selector:
    matchLabels:
      io.mad.service: mad-lesson
  strategy: {}
  template:
    metadata:
      labels:
        io.mad.service: mad-lesson
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: env-lesson
            - configMapRef:
                name: env-keycloak-secrets
          image: ghcr.io/mad-goat-project/mad-lessons-service:main
          name: mad-lesson
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: 500m
              memory: "500Mi"
            requests:
              cpu: 250m
              memory: "250Mi"
      restartPolicy: Always
