apiVersion: v1
kind: Service
metadata:
  labels:
    io.mad.service: mad-lesson
  name: mad-lesson
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    io.mad.service: mad-lesson
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-prefix-lessons
spec:
  stripPrefixRegex:
    regex:
      - "/api/lessons"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: mad-lesson
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match:  Host(`madgoat.tech`) && PathPrefix(`/api/lessons`)
      middlewares:
        - name: strip-prefix-lessons
      services:
        - kind: Service
          name: mad-lesson
          namespace: default
          port: 3000
