apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.mad.service: scoreboard
  name: scoreboard
spec:
  replicas: 1
  selector:
    matchLabels:
      io.mad.service: scoreboard
  strategy: {}
  template:
    metadata:
      labels:
        io.mad.network/mad-network: "true"
        io.mad.service: scoreboard
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: env-scoreboard
            - configMapRef:
                name: env-keycloak-secrets
          image: ghcr.io/mad-goat-project/mad-scoreboard-service:main
          name: mad-scoreboard
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: 500m
              memory: "500Mi"
            requests:
              cpu: 250m
              memory: "250Mi"
      restartPolicy: Always
