{{ range .Values.dbs }}
{{ if .pvc}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.mad.service: {{ .name }}-claim0
  name: {{ .name }}-claim0
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
{{- end}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.mad.service: {{ .name }}
  name: {{ .name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.mad.service: {{ .name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.mad.network/mad-network: "true"
        io.mad.service: {{ .name }}
    spec:
      {{ if hasKey . "initialization" }}
      initContainers:
        - name: default-data-loader
          image: {{ .initialization.image }}
          env:
            - name: TARGET_PATH
              value: "{{.initialization.path}}" # Destination path inside the pod
          volumeMounts:
            - mountPath: {{.initialization.path}}
              name: {{ .name }}-claim0
      {{ end }}
      containers:
      - securityContext:
          {{- if not $.Values.vulnerabilities.k01_runAsRoot }}
          runAsNonRoot: true
          runAsUser: 999
          allowPrivilegeEscalation: false
          {{- end }}
          {{- if not $.Values.vulnerabilities.k01_readOnlyRootFs }}
          readOnlyRootFilesystem: true
          {{- end }}
        resources:
          limits:
            cpu: {{ .resources.limits.cpu }}
            memory: "{{ .resources.limits.memory }}"
          requests:
            cpu: {{ .resources.requests.cpu }}
            memory: "{{ .resources.requests.memory }}"
          {{- if .envFromConfigMaps }}
        envFrom:
            {{- range .envFromConfigMaps }}
          - configMapRef:
              name: {{ . }}
            {{- end }}
          {{- end }}
        {{ if eq .type "postgres" }}
        image: postgres:14.1-alpine
        name: {{ .name }}
        ports:
          - containerPort: 5432
        {{- else if eq .type  "mongo" }}
        image: mongo:6.0
        name: {{ .name }}
        ports:
          - containerPort: 27017
        {{- else if eq .type "minio" }}
        image: ghcr.io/mad-goat-project/mc-minio:mc-minio
        name: minio
        ports:
          - containerPort: 9000
            protocol: TCP
          - containerPort: 9001
            protocol: TCP
        args:
          - server
          - /data
          - --console-address
          - :9001
        lifecycle:
          postStart:
            exec:
              command:
                - /bin/sh
                - -c
                - |
                  sleep 5  # Give MinIO time to initialize
                  mc alias set local http://localhost:9000 minio minio123
                  mc admin info local
                  mc mb local/mad-images
                  mc anonymous set public local/mad-images
        {{- end }}
        volumeMounts:
        {{ if eq .type  "postgres" }}
          - mountPath: /var/lib/postgresql/data
        {{ else if eq .type  "mongo" }}
          - mountPath: /data/db
        {{ else if eq .type  "minio" }}
          - mountPath: /data
        {{- end }}
            name: {{ .name }}-claim0
      restartPolicy: Always
      volumes:
        - name: {{ .name }}-claim0
          persistentVolumeClaim:
            claimName: {{ .name }}-claim0
{{- end }}