{{- if not .Values.vulnerabilities.k03_plaintextConfigMapSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-keycloak
  labels:
    io.mad.vuln: k03-plaintextConfigMapSecrets
type: Opaque
stringData:
  KEYCLOAK_ADMIN_PASSWORD: "admin"
  POSTGRES_PASSWORD: "password"
  KC_DB_PASSWORD: "password"
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-minio
  labels:
    io.mad.vuln: k03-plaintextConfigMapSecrets
type: Opaque
stringData:
  MINIO_ROOT_PASSWORD: "minio123"
  MINIO_SECRET_KEY: "mysupersecretkey"
{{- end }}
