{{- if not .Values.vulnerabilities.k09_sharedServiceAccount }}
{{- range .Values.core }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-{{ .name }}
  namespace: default
  labels:
    io.mad.service: {{ .name }}
automountServiceAccountToken: false
{{- end }}
{{- range .Values.dbs }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-{{ .name }}
  namespace: default
  labels:
    io.mad.service: {{ .name }}
automountServiceAccountToken: false
{{- end }}
{{- end }}
